[CmdletBinding()]
param([switch]$Resume,[switch]$ShowHostWindow)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=(Resolve-Path(Join-Path$PSScriptRoot'..')).Path;Set-Location$root
& git fetch origin;if($LASTEXITCODE-ne0){throw 'git fetch failed'};$head=(& git rev-parse HEAD).Trim();$remote=(& git rev-parse origin/main).Trim();if($head-ne$remote){throw "Local HEAD $head != origin/main $remote. Synchronize before study."};$dirty=@(& git status --porcelain);if($dirty.Count-gt0){throw "Working tree is not clean. Synchronize/clean it before study.`n$($dirty-join"`n")"}
. (Join-Path$PSScriptRoot'Range-Utils.ps1')
$studyPath=Join-Path$root'studies\STU001__UTG-BB__FULLTREE__V1.json';$study=Get-Content$studyPath -Raw -Encoding UTF8|ConvertFrom-Json;$boardsPath=Join-Path$root$study.board_file;$oopRangePath=Join-Path$root$study.ranges.oop_file;$ipRangePath=Join-Path$root$study.ranges.ip_file;$oop=@(Convert-TexasSolverRangeTo1326 -Path$oopRangePath);$ip=@(Convert-TexasSolverRangeTo1326 -Path$ipRangePath)
$effective=[ordered]@{runner=[ordered]@{maxIterations=[int]$study.solve.max_iterations;targetExploitability=[double]$study.solve.target_exploitability};config=[ordered]@{oopRange=$oop;ipRange=$ip;startingPot=[double]$study.game.flop_pot_native;effectiveStack=[double]$study.game.effective_stack_native;rakeRate=0;rakeCap=0;oopFlopBet=$study.tree.flop.bet;ipFlopBet=$study.tree.flop.bet;oopFlopRaise=$study.tree.flop.raise;ipFlopRaise=$study.tree.flop.raise;oopTurnBet=$study.tree.turn.bet;ipTurnBet=$study.tree.turn.bet;oopTurnRaise=$study.tree.turn.raise;ipTurnRaise=$study.tree.turn.raise;oopTurnDonk=$study.tree.turn.donk;oopRiverBet=$study.tree.river.bet;ipRiverBet=$study.tree.river.bet;oopRiverRaise=$study.tree.river.raise;ipRiverRaise=$study.tree.river.raise;oopRiverDonk=$study.tree.river.donk;maxRaiseNumber=[int]$study.tree.max_normal_raises;addAllinThreshold=[int]$study.tree.add_allin_threshold_percent;addAllinFlopIp=$true;addAllinTurnIp=$true;addAllinRiverIp=$true;addAllinFlopOop=$true;addAllinTurnOop=$true;addAllinRiverOop=$true}}
[IO.Directory]::CreateDirectory((Join-Path$root'.tmp'))|Out-Null;$tmpConfig=Join-Path$root'.tmp\STU001-effective.json';$effective|ConvertTo-Json -Depth 100|Set-Content -LiteralPath$tmpConfig -Encoding UTF8
$stamp=Get-Date -Format'yyyyMMdd-HHmmss';$runName="STU001__BRD001__RUN-$stamp";$workDir=Join-Path$root("output\$runName");if($Resume){$latest=Get-ChildItem(Join-Path$root'output') -Directory -Filter'STU001__BRD001__RUN-*' -ErrorAction SilentlyContinue|sort Name -Descending|select -First 1;if($null-eq$latest){throw 'No incomplete STU001 output found for resume'};$workDir=$latest.FullName;$runName=$latest.Name}
& (Join-Path$root'tsgpu-batch.ps1') -Config$tmpConfig -Boards$boardsPath -OutputDirectory$workDir -Resume:$Resume -ShowHostWindow:$ShowHostWindow
$summary=@(Import-Csv(Join-Path$workDir'batch-summary.csv'));if($summary.Count-ne286-or@($summary|?{$_.status-ne'done'}).Count-ne0){throw 'Study validation failed: expected 286 completed boards'};foreach($row in$summary){$d=Join-Path$workDir('{0:D4}_{1}'-f[int]$row.index,(($row.board-replace'[^0-9A-Za-z]+','_').Trim('_')));$m=Get-Content(Join-Path$d'tree.meta.json') -Raw|ConvertFrom-Json;if(-not$m.full_tree_validated){throw "Invalid tree export at $($row.board)"}}
function Sha([string]$p){(Get-FileHash -LiteralPath$p -Algorithm SHA256).Hash.ToLowerInvariant()};Copy-Item$studyPath(Join-Path$workDir'INPUT_STUDY.json');Copy-Item$boardsPath(Join-Path$workDir'INPUT_BOARDS.txt');Copy-Item$oopRangePath(Join-Path$workDir'INPUT_RANGE_OOP.txt');Copy-Item$ipRangePath(Join-Path$workDir'INPUT_RANGE_IP.txt');Copy-Item$tmpConfig(Join-Path$workDir'INPUT_EFFECTIVE_CONFIG.json')
$manifest=[ordered]@{schema_version=1;study_id='STU001';run_id=$runName;created_at=(Get-Date).ToString('o');board_count=286;result_contract='one complete validated postflop tree per flop';git_source_commit=$head;inputs=[ordered]@{study_sha256=Sha$studyPath;boards_sha256=Sha$boardsPath;oop_range_sha256=Sha$oopRangePath;ip_range_sha256=Sha$ipRangePath;effective_config_sha256=Sha$tmpConfig}};$manifest|ConvertTo-Json -Depth 20|Set-Content(Join-Path$workDir'RUN_MANIFEST.json') -Encoding UTF8
$resultsRoot=Join-Path$root'results';$finalDir=Join-Path$resultsRoot$runName;if(Test-Path$finalDir){throw "Result directory already exists: $finalDir"};Move-Item -LiteralPath$workDir -Destination$finalDir
& git add -- "results/$runName";if($LASTEXITCODE-ne0){throw 'git add result failed'};& git commit -m "study STU001: full-tree BRD001 $stamp";if($LASTEXITCODE-ne0){throw 'git commit result failed'};& git pull --rebase origin main;if($LASTEXITCODE-ne0){throw 'git pull --rebase failed; result remains committed locally'};& git push origin HEAD:main;if($LASTEXITCODE-ne0){throw 'git push failed; result remains committed locally'}
Write-Host '';Write-Host 'STUDY COMPLETE AND PUSHED';Write-Host "Result: results/$runName"
